#Embedded file name: wx/__version__.py
VERSION_STRING = '2.8.9.1'
MAJOR_VERSION = 2
MINOR_VERSION = 8
RELEASE_VERSION = 9
SUBREL_VERSION = 1
VERSION = (MAJOR_VERSION,
 MINOR_VERSION,
 RELEASE_VERSION,
 SUBREL_VERSION,
 '')
